# Site settings
title: "Pandora小窝"
description: "记录思考和日常"
baseurl: "/textlog" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://Jay-R-J.github.io"
author: "Jay"

# Build settings
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
