# Site settings
title: "Minimalist Blog"
description: "极简技术速查表 | 一键命令、避坑指南、部署报错快速解决方案"
baseurl: "/textlog" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://Jay-R-J.github.io"
author: "Jay"

# Build settings
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
